CREATE DATABASE IF NOT EXISTS loja4
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE loja4;

CREATE TABLE IF NOT EXISTS usuarios (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    Senha VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS vendas (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(150) NOT NULL,
    Estado VARCHAR(100) NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    Bairro VARCHAR(100) NOT NULL,
    Rua VARCHAR(150) NOT NULL,
    Numero VARCHAR(20) NOT NULL,
    Produtos TEXT NOT NULL,
    Total DECIMAL(10,2) NOT NULL
);
